#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_inactive_separator = "slant"
    buffer_index_type = 4
#    enable_tabline_filetype_icon = false
    enable_statusline_mode = true
    # left sections of statusline
    bootstrap_before = "myspacevim#before"
    # autocomplete_method = "coc"

[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "smart"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "lang#go"

[[layers]]
    name = "tools"

[[layers]]
    name = "colorscheme"

[[layers]]
    name = "ctrlp"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "debug"

[[custom_plugins]]
  repo = "hashivim/vim-terraform"
  meged = false
